modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="shockwave"
version="1.0.0"
displayName="Shockwave"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Noah V, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.shockwave]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"


[[dependencies.shockwave]]
    modId="pehkui"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.shockwave]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

