modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="guilded_smp_resources"
version="1.1.1"
displayName="Gilded SMP Resources"
displayURL="https://kreshn.dev/"
credits="Models made using Blockbench - https://blockbench.net"
authors="Kreshn"
description="A resource mod for the Gilded SMP! This contains sensitive data, do not leak to the public."

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.guilded_smp_resources]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"


[[dependencies.guilded_smp_resources]]
    modId="pehkui"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.guilded_smp_resources]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

