modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="quality_of_life"
version="1.1.1"
displayName="Quality of Life"
displayURL="https://mcreator.net"
credits="Models made using Blockbench - https://blockbench.net"
authors="Kreshn"
description="A QoL Mod enhancing various parts of the minecraft experience!"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.quality_of_life]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"


[[dependencies.quality_of_life]]
    modId="pehkui"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.quality_of_life]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.quality_of_life]]
    modId="playeranimator"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

